### ISSUE TITLE
Trouble in sdcardlogexample.ino

### ISSUE THREAD

**Issue by eron93br** [rickkas7/SdCardLogHandlerRK#1]
hello rickkas7! Thanks for your contribution. I'm trying to run the sdcardlogexample.ino example in my electron board, I got the following error on the web ide

"lib/SdCardLogHandlerRK/SdCardLogHandlerRK.h:36:95: 'LogCategoryFilters' has not been declared "

Could you explain which variable is this one? And how could I fix this problem and flash the code?

**Comment by rickkas7** [comment]
You most likely do not have system firmware 0.6.0 or later on the device. You should upgrade to 0.7.0 (the current release) and make sure you're targeting that in your build and LogCategoryFilters should be defined.
